before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - git rm --cached .gitlab-ci.yml
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  type: deploy
  environment:
    name: staging
    url: demo603.rp-demo.ru
  script:
    - ssh -A root@5.188.143.56 -p 3117 "cd /var/www/studysagitova/app && git checkout master && git pull origin master && ../chmod && exit"
  only:
    - master
